
export const registerationConstant = {
 USER_RESISTERATATION_REQUEST:'USER_RESISTERATATION_REQUEST',
 USER_RESISTERATATION_SUCCESS:'USER_RESISTERATATION_SUCCESS',
 USER_RESISTERATATION_FAILURE:'USER_RESISTERATATION_FAILURE',
 GET_ALL_USER_REQUEST:'GET_ALL_USER_REQUEST',
 GET_ALL_USER_SUCCESS:'GET_ALL_USER_SUCCESS',
 GET_ALL_USER_FAILURE:'GET_ALL_USER_FAILURE'
 
}
export const LoginConstant = {
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE',
    
}

export const messageConstants = {
    GET_CONVERSATIONS_REQUEST: 'GET_CONVERSATIONS_REQUEST',
    GET_CONVERSATIONS_SUCCESS: 'GET_CONVERSATIONS_SUCCESS',
    GET_CONVERSATIONS_FAILURE: 'GET_CONVERSATIONS_FAILURE',
}
export const assesmentConstants = {
    ADD_NEW_ASSESMENT_REQUEST:'ADD_NEW_ASSESMENT_REQUEST',
    ADD_NEW_ASSESMENT_SUCCESS:'ADD_NEW_ASSESMENT_SUCCESS',
    ADD_NEW_ASSESMENT_FAILURE:'ADD_NEW_ASSESMENT_FAILURE',

    GET_ALL_ASSESMENT_REQUEST:'GET_ALL_ASSESMENT_REQUEST',
    GET_ALL_ASSESMENT_SUCCESS:'GET_ALL_ASSESMENT_SUCCESS',
    GET_ALL_ASSESMENT_FAILURE:'GET_ALL_ASSESMENT_FAILURE',
  
    GET_ASSESMENT_BYID_REQUEST:'GET_ASSESMENT_BYID_REQUEST',
    GET_ASSESMENT_BYID_SUCCESS:'GET_ASSESMENT_BYID_SUCCESS',
    GET_ASSESMENT_BYID_FAILURE:'GET_ASSESMENT_BYID_FAILURE'

}  

export const userAssesmentConstant = {
    ADD_NEW_ASSESMENT_TEST_REQUEST:'ADD_NEW_ASSESMENT_TEST_REQUEST',
    ADD_NEW_ASSESMENT_TEST_SUCCESS:'ADD_NEW_ASSESMENT_TEST_SUCCESS',
    ADD_NEW_ASSESMENT_TEST_FAILURE:'ADD_NEW_ASSESMENT_TEST_FAILURE',

    GET_NEW_ASSEMENT_TEST_REQUEST:'GET_NEW_ASSEMENT_TEST_REQUEST',
    GET_NEW_ASSEMENT_TEST_SUCCESS:'GET_NEW_ASSEMENT_TEST_SUCCESS',
    GET_NEW_ASSEMENT_TEST_FAILURE:'GET_NEW_ASSEMENT_TEST_FAILURE'
}
